### ISSUE TITLE
Feature request: automatically generate schema visualisation after running `prisma db push`

### ISSUE THREAD

**Issue by Gintasz** [Ovyerus/prismaliser#54]
I think this tool is great, however, it's a bit annoying to copy-paste Prisma schema into the [prismaliser.app](https://prismaliser.app/) website. It could be an interesting feature to have a .png image automatically generated each time you run `prisma db push` command. It would be placed in the same folder along with the schema file and would always be up to date.

**Comment by vprasanth** [comment]
Like built into the official CLI? Yeah that would be pretty great. (via a flag of course).

**Comment by Ovyerus** [comment]
This is out of scope for Prismaliser IMO, it's intended to help visualise already complete schemas, or to edit them alongside the visualisation in the browser. A few tools already exist that do what you want (though on `prisma generate` instead of `db push`), using custom generators like the JS client. [prisma-dbml-generator](https://github.com/notiz-dev/prisma-dbml-generator) and [prisma-erd-geneator](https://github.com/keonik/prisma-erd-generator) both seem to achieve the same goal, just with different styling/layout between them.
